# Generated by Django 5.0.2 on 2024-03-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "brand",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "company",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flashnews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField(default=None)),
                ("url", models.URLField(max_length=255)),
                ("pic_url", models.URLField(max_length=255)),
                ("ptime", models.DateTimeField()),
                ("user_id", models.BigIntegerField(default=None)),
                ("user_name", models.CharField(max_length=255)),
                ("user_verified", models.CharField(max_length=255)),
                ("related_car", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(max_length=255)),
                ("post_platform", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GtmInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.IntegerField(default=None)),
                ("car_name", models.CharField(default=None, max_length=255)),
                ("pic_url", models.URLField(default=None, max_length=255)),
                ("price", models.CharField(default=None, max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("update_time", models.DateTimeField()),
                ("sell_status", models.CharField(default=None, max_length=255)),
                ("car_url", models.URLField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HeaderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("market_segmentation", models.CharField(default="全部", max_length=255)),
                ("car", models.CharField(default="全部", max_length=255)),
                ("sale", models.IntegerField(default=None)),
                ("share", models.FloatField(default=None)),
                ("w2w", models.FloatField(default=None)),
                ("wow", models.FloatField(default=None)),
                ("year", models.IntegerField(default=None)),
                ("week", models.IntegerField(default=None)),
                ("area", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LongNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default=None)),
                ("content", models.TextField(default=None)),
                ("summary", models.TextField(default=None)),
                ("url", models.URLField(max_length=255)),
                ("ptime", models.DateTimeField()),
                ("post_platform", models.CharField(max_length=255)),
                ("platform_avatar", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PcautoCars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.IntegerField(default=None)),
                ("car_name", models.CharField(default=None, max_length=255)),
                ("pic_url", models.URLField(default=None, max_length=255)),
                ("price", models.CharField(default=None, max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("update_time", models.DateTimeField()),
                ("sell_status", models.CharField(default=None, max_length=255)),
                ("car_url", models.URLField(default=None, max_length=255)),
                ("car_class", models.CharField(default="未知", max_length=255)),
                ("company", models.CharField(default="未知", max_length=255)),
                ("brand", models.CharField(default="未知", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SinaResou",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("hot_value", models.IntegerField(default=0)),
                ("url", models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=16, unique=True, verbose_name="用户名"),
                ),
                ("phone", models.BigIntegerField(unique=True, verbose_name="手机号")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "car",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("length", models.IntegerField(default=None)),
                ("width", models.IntegerField(default=None)),
                ("height", models.IntegerField(default=None)),
                ("car_type", models.CharField(default=None, max_length=255)),
                ("car_class", models.CharField(default=None, max_length=255)),
                ("car_body_form", models.CharField(default=None, max_length=255)),
                ("price_interval", models.CharField(default=None, max_length=255)),
                (
                    "brands",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="index.brand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="index.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="index.company",
            ),
        ),
        migrations.CreateModel(
            name="CompanySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale", models.IntegerField(default=None)),
                ("mom", models.FloatField(default=None)),
                ("m2m", models.FloatField(default=None)),
                ("month", models.IntegerField(default=None)),
                ("year", models.IntegerField(default=None)),
                ("year_sale", models.IntegerField(default=None)),
                ("category", models.CharField(default=None, max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_sales",
                        to="index.brand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_sales",
                        to="index.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promotion", models.TextField(default=None)),
                ("price", models.CharField(default=None, max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("source", models.CharField(max_length=255)),
                ("link", models.URLField(max_length=255)),
                ("area", models.CharField(default=None, max_length=255)),
                ("summary", models.TextField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_info",
                        to="index.brand",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_info",
                        to="index.cars",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_info",
                        to="index.company",
                    ),
                ),
            ],
        ),
    ]
